### ISSUE TITLE
CLI doesn't seem to work

### ISSUE THREAD

**Issue by kevinvugts** [instantcommerce/instant-sdk-examples#18]
Hello,

The command "instant select", "instant add", "instant publish" don't seem to work. 
When running instant whoami it correclty returns the email adres I am logged in with.

However, when running instant select. I am not getting a list of organizations back. Instead I get an empty: "Select an organization:"

I am running on a free plan. Is this limited for paid only?
Or is this is a bug? 

Best Regards,

**Comment by leeuwis** [comment]
Hi @kevinvugts, I can understand the confusion, I expect you are trying to login with your `instant.so` account for our new Native Shopify solution, while this SDK has been created for our Headless Shopify solution (which is a different product).

In the future we also want to add more developer tools to the `instant.so` platform. Can you let me know what you wanted to build with the SDK so our team is aware of the potential use cases? You can also DM me on https://twitter.com/doeketomas or in our Slack community: https://instant.so/community!
